### ISSUE TITLE
NullPointerException from VisibilityControlFilters

### ISSUE THREAD

**Issue by dnahodil** [aodn/aatams#177]
**Steps to reproduce**
* Log in as a user
* On the animal release list click on the (i) next a release that the user owns (*my release was protected but I'm not sure if that matters*)
* Click the 'edit' button
* Click the 'update' button (you don't need to change any fields)

**What should happen**
No errors in server log

**What does happen**
A NullPointerException is logged

**Comment by dnahodil** [comment]
<pre>
2015-01-28 16:37:49,566 [http-8080-1] [admin] ERROR GrailsExceptionResolver - Exception occurred when processing request: [POST] /aatams/animalRelease/index - parameters:
releaseDateTime_hour: 14
releaseDateTime_minute: 15
project.id: 174
captureLocation_lon: 10.1234
captureLocality: Neptune Islands
releaseDateTime_zone: Australia/Hobart
embargoDate: date.struct
speciesName: 37010003 - Carcharodon carcharias (White Shark)
releaseLocality: Neptune Islands
_action_update: Update
captureDateTime_second: 00
captureDateTime: struct
releaseLocation: POINT(30.1234 40.1234) , -1
projectId: 174
speciesId: 132
version: 10
id: 291
releaseDateTime: struct
releaseDateTime_second: 00
releaseDateTime_month: 2
releaseLocation_lat: 40.1234
releaseDateTime_year: 2010
captureDateTime_month: 2
sex.id: 136
captureLocation: POINT(10.1234 20.1234) , -1
captureMethod.id: 151
captureDateTime_zone: Australia/Hobart
animal.id: 288
captureLocation_srid: -1
embargoDate_day: 16
captureLocation_pointInputTextField: 20.1234°N 10.1234°E (datum:)
releaseLocation_srid: -1
captureDateTime_year: 2010
embargoDate_year: 2010
releaseLocation_pointInputTextField: 40.1234°N 30.1234°E (datum:)
releaseLocation_lon: 30.1234
captureDateTime_day: 16
captureDateTime_minute: 10
captureLocation_lat: 20.1234
embargoDate_month: 2
captureDateTime_hour: 14
comments: 
releaseDateTime_day: 16
Stacktrace follows:
java.lang.NullPointerException: Cannot get property 'animalReleaseInstance' on null object
	at au.org.emii.aatams.VisibilityControlFilters$_closure1_closure3_closure5.doCall(VisibilityControlFilters.groovy:48)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:359)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:275)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:344)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:272)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81)
	at org.apache.shiro.grails.SavedRequestFilter.doFilter(SavedRequestFilter.java:55)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by anguss00** [comment]
I'm on this

**Comment by dnahodil** [comment]
Bad news, @anguss00. I'm on it. Sorry :)

**Comment by anguss00** [comment]
I'm not on this ;-)
