### ISSUE TITLE
Receiver Export sort by "uploader" results in exception

### ISSUE THREAD

**Issue by jkburges** [aodn/aatams#65]
The following exception occurs when sorting by uploader, as a non-admin user:

```log4j
java.lang.NullPointerException: Cannot get property 'id' on null object
	at au.org.emii.aatams.ReceiverDownloadFileFilters$_applyVisibility_closure2.doCall(ReceiverDownloadFileFilters.groovy:27)
	at au.org.emii.aatams.ReceiverDownloadFileFilters.applyVisibility(ReceiverDownloadFileFilters.groovy:25)
	at au.org.emii.aatams.ReceiverDownloadFileFilters$_closure1_closure3_closure4.doCall(ReceiverDownloadFileFilters.groovy:16)

[cut]
```

**Steps to reproduce:**
1. Log in as **non-admin** user.
2. Go to: https://aatams.emii.org.au/aatams/receiverDownloadFile/list
3. Click column heading "Uploader" twice.

**What happens:**
The above exception occurs.

**What should happen:**
The receiver export list should be sorted (desc) by uploader.

**Comment by xhoenner** [comment]
@jkburges this issue can probably be closed too as I've just tried to recreate it and didn't get an error.

**Comment by jkburges** [comment]
I think @dnahodil fixed this actually.
